platform :ios, '12.4'
pod 'AppLovinSDK','12.2.1'

pod 'AppLovinMediationAmazonAdMarketplaceAdapter', '4.7.8.0'
pod 'AmazonPublisherServicesSDK', '4.7.8'
pod 'Google-Mobile-Ads-SDK', '11.0.0'

{{#applovin.MintegralAdapter}}
pod 'AppLovinMediationMintegralAdapter', '7.5.7.0.0' 
{{/applovin.MintegralAdapter}}

{{#applovin.InMobiAdapter}}
pod 'AppLovinMediationInMobiAdapter', '10.6.4.0' 
{{/applovin.InMobiAdapter}}

{{#applovin.IronSourceAdapter}}
pod 'AppLovinMediationIronSourceAdapter', '7.8.0.0.0' 
{{/applovin.IronSourceAdapter}}

{{#applovin.VungleAdapter}}
pod 'AppLovinMediationVungleAdapter', '7.2.2.0' 
{{/applovin.VungleAdapter}}

{{#applovin.MaioAdapter}}
pod 'AppLovinMediationMaioAdapter', '2.1.2.0' 
{{/applovin.MaioAdapter}}

{{#applovin.FacebookAdapter}}
pod 'AppLovinMediationFacebookAdapter', '6.14.0.1' 
{{/applovin.FacebookAdapter}}

{{#applovin.MyTargetAdapter}}
pod 'AppLovinMediationMyTargetAdapter', '5.20.1.1' 
{{/applovin.MyTargetAdapter}}

{{#applovin.UnityAdsAdapter}}
pod 'AppLovinMediationUnityAdsAdapter', '4.9.2.1' 
{{/applovin.UnityAdsAdapter}}

{{#applovin.OguryPresageAdapter}}
pod 'AppLovinMediationOguryPresageAdapter', '4.2.2.1' 
{{/applovin.OguryPresageAdapter}}

{{#applovin.FyberAdapter}}
pod 'AppLovinMediationFyberAdapter', '8.2.5.2' 
{{/applovin.FyberAdapter}}

{{#applovin.GoogleAdManagerAdapter}}
pod 'AppLovinMediationGoogleAdManagerAdapter', '10.14.0.0' 
{{/applovin.GoogleAdManagerAdapter}}

{{#applovin.GoogleAdapter}}
pod 'AppLovinMediationGoogleAdapter', '10.14.0.1' 
{{/applovin.GoogleAdapter}}

{{#applovin.ChartboostAdapter}}
pod 'AppLovinMediationChartboostAdapter', '9.6.0.0' 
{{/applovin.ChartboostAdapter}}

{{#applovin.ByteDanceAdapter}}
pod 'AppLovinMediationByteDanceAdapter', '5.7.0.8.0' 
{{/applovin.ByteDanceAdapter}}

{{#applovin.BidMachineAdapter}}
pod 'AppLovinMediationBidMachineAdapter', '2.5.1.0.0'
{{/applovin.BidMachineAdapter}}
