platform :ios, '12.4'
pod 'AppLovinSDK','11.11.3'

pod 'AppLovinMediationAmazonAdMarketplaceAdapter', '4.7.5.0'
pod 'AmazonPublisherServicesSDK', '4.7.5'

{{#applovin.MintegralAdapter}}
pod 'AppLovinMediationMintegralAdapter', '7.4.3.0.0' 
{{/applovin.MintegralAdapter}}

{{#applovin.AdColonyAdapter}}
pod 'AppLovinMediationAdColonyAdapter', '4.9.0.0.4' 
{{/applovin.AdColonyAdapter}}

{{#applovin.InMobiAdapter}}
pod 'AppLovinMediationInMobiAdapter', '10.5.6.0' 
{{/applovin.InMobiAdapter}}

{{#applovin.IronSourceAdapter}}
pod 'AppLovinMediationIronSourceAdapter', '7.5.0.0.0' 
{{/applovin.IronSourceAdapter}}

{{#applovin.VungleAdapter}}
pod 'AppLovinMediationVungleAdapter', '7.0.1.0' 
{{/applovin.VungleAdapter}}

{{#applovin.MaioAdapter}}
pod 'AppLovinMediationMaioAdapter', '1.6.3.3' 
{{/applovin.MaioAdapter}}

{{#applovin.FacebookAdapter}}
pod 'AppLovinMediationFacebookAdapter', '6.14.0.0' 
{{/applovin.FacebookAdapter}}

{{#applovin.MyTargetAdapter}}
pod 'AppLovinMediationMyTargetAdapter', '5.19.0.0' 
{{/applovin.MyTargetAdapter}}

{{#applovin.UnityAdsAdapter}}
pod 'AppLovinMediationUnityAdsAdapter', '4.8.0.1' 
{{/applovin.UnityAdsAdapter}}

{{#applovin.OguryPresageAdapter}}
pod 'AppLovinMediationOguryPresageAdapter', '4.2.0.0' 
{{/applovin.OguryPresageAdapter}}

{{#applovin.FyberAdapter}}
pod 'AppLovinMediationFyberAdapter', '8.2.4.0' 
{{/applovin.FyberAdapter}}

{{#applovin.GoogleAdManagerAdapter}}
pod 'AppLovinMediationGoogleAdManagerAdapter', '10.10.0.0' 
{{/applovin.GoogleAdManagerAdapter}}

{{#applovin.GoogleAdapter}}
pod 'AppLovinMediationGoogleAdapter', '10.10.0.0' 
{{/applovin.GoogleAdapter}}

{{#applovin.ChartboostAdapter}}
pod 'AppLovinMediationChartboostAdapter', '9.4.0.1' 
{{/applovin.ChartboostAdapter}}

{{#applovin.ByteDanceAdapter}}
pod 'AppLovinMediationByteDanceAdapter', '5.4.1.0.0' 
{{/applovin.ByteDanceAdapter}}

{{#applovin.BidMachineAdapter}}
pod 'AppLovinMediationBidMachineAdapter', '2.3.0.2.0'
{{/applovin.BidMachineAdapter}}
