platform :ios, '12.4'
pod 'AppLovinSDK','13.0.0'

pod 'AppLovinMediationAmazonAdMarketplaceAdapter', '4.10.0.0'
pod 'AmazonPublisherServicesSDK', '4.10.0'
pod 'Google-Mobile-Ads-SDK', '11.10.0'

{{#applovin.MintegralAdapter}}
pod 'AppLovinMediationMintegralAdapter', '7.7.2.0.1' 
{{/applovin.MintegralAdapter}}

{{#applovin.InMobiAdapter}}
pod 'AppLovinMediationInMobiAdapter', '10.7.5.1' 
{{/applovin.InMobiAdapter}}

{{#applovin.IronSourceAdapter}}
pod 'AppLovinMediationIronSourceAdapter', '8.3.0.0.1' 
{{/applovin.IronSourceAdapter}}

{{#applovin.VungleAdapter}}
pod 'AppLovinMediationVungleAdapter', '7.4.1.1' 
{{/applovin.VungleAdapter}}

{{#applovin.MaioAdapter}}
pod 'AppLovinMediationMaioAdapter', '2.1.5.0' 
{{/applovin.MaioAdapter}}

{{#applovin.FacebookAdapter}}
pod 'AppLovinMediationFacebookAdapter', '6.15.2.1' 
{{/applovin.FacebookAdapter}}

{{#applovin.MyTargetAdapter}}
pod 'AppLovinMediationMyTargetAdapter', '5.21.9.0' 
{{/applovin.MyTargetAdapter}}

{{#applovin.UnityAdsAdapter}}
pod 'AppLovinMediationUnityAdsAdapter', '4.12.3.0' 
{{/applovin.UnityAdsAdapter}}

{{#applovin.OguryPresageAdapter}}
pod 'AppLovinMediationOguryPresageAdapter', '4.4.1.0' 
{{/applovin.OguryPresageAdapter}}

{{#applovin.FyberAdapter}}
pod 'AppLovinMediationFyberAdapter', '8.3.2.1' 
{{/applovin.FyberAdapter}}

{{#applovin.GoogleAdManagerAdapter}}
pod 'AppLovinMediationGoogleAdManagerAdapter', '11.10.0.0' 
{{/applovin.GoogleAdManagerAdapter}}

{{#applovin.GoogleAdapter}}
pod 'AppLovinMediationGoogleAdapter', '11.10.0.0' 
{{/applovin.GoogleAdapter}}

{{#applovin.ChartboostAdapter}}
pod 'AppLovinMediationChartboostAdapter', '9.7.0.2' 
{{/applovin.ChartboostAdapter}}

{{#applovin.ByteDanceAdapter}}
pod 'AppLovinMediationByteDanceAdapter', '6.2.0.7.2' 
{{/applovin.ByteDanceAdapter}}

{{#applovin.BidMachineAdapter}}
pod 'AppLovinMediationBidMachineAdapter', '3.0.1.0.0'
{{/applovin.BidMachineAdapter}}
